app:
  model_backend: "sentence_transformers"  # or "tfidf"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  similarity_threshold: 0.55
  top_k_roles: 5


paths:
  skills_db: "data/skills_database.json"
  job_desc_dir: "data/job_descriptions"
  sample_resumes: "data/sample_resumes"